Document: libfcdpp
Title: Debian libfcdpp Manual
Author: <insert document author here>
Abstract: This manual describes what libfcdpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfcdpp/libfcdpp.sgml.gz

Format: postscript
Files: /usr/share/doc/libfcdpp/libfcdpp.ps.gz

Format: text
Files: /usr/share/doc/libfcdpp/libfcdpp.text.gz

Format: HTML
Index: /usr/share/doc/libfcdpp/html/index.html
Files: /usr/share/doc/libfcdpp/html/*.html
