Document: libfdcpp
Title: Debian libfdcpp Manual
Author: <insert document author here>
Abstract: This manual describes what libfdcpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfdcpp/libfdcpp.sgml.gz

Format: postscript
Files: /usr/share/doc/libfdcpp/libfdcpp.ps.gz

Format: text
Files: /usr/share/doc/libfdcpp/libfdcpp.text.gz

Format: HTML
Index: /usr/share/doc/libfdcpp/html/index.html
Files: /usr/share/doc/libfdcpp/html/*.html
