Document: libfdcpp1
Title: Debian libfdcpp1 Manual
Author: <insert document author here>
Abstract: This manual describes what libfdcpp1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfdcpp1/libfdcpp1.sgml.gz

Format: postscript
Files: /usr/share/doc/libfdcpp1/libfdcpp1.ps.gz

Format: text
Files: /usr/share/doc/libfdcpp1/libfdcpp1.text.gz

Format: HTML
Index: /usr/share/doc/libfdcpp1/html/index.html
Files: /usr/share/doc/libfdcpp1/html/*.html
