Document: libfcdpp1
Title: Debian libfcdpp1 Manual
Author: <insert document author here>
Abstract: This manual describes what libfcdpp1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfcdpp1/libfcdpp1.sgml.gz

Format: postscript
Files: /usr/share/doc/libfcdpp1/libfcdpp1.ps.gz

Format: text
Files: /usr/share/doc/libfcdpp1/libfcdpp1.text.gz

Format: HTML
Index: /usr/share/doc/libfcdpp1/html/index.html
Files: /usr/share/doc/libfcdpp1/html/*.html
